# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "elastic/sles-11-x86_64"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provider 'virtualbox' do |v|
      v.linked_clone = true
  end

  # map the ports for intersystems cache
  config.vm.network "forwarded_port", guest: 1972, host: 1972
  config.vm.network "forwarded_port", guest: 8972, host: 8972

  # disable vbox addons update
  config.vbguest.auto_update = false

  # disable sync of local dir to /vagrant
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # register suse
  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.playbook = "ansible/suse-register.yaml"
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo zypper ref
     sudo zypper --non-interactive up
     sudo zypper clean
  SHELL

  config.vm.provision :reload

end
