---
- hosts: all
  gather_facts: True
  vars:
    - hs_distribution_version: 2018.1.0.513.0
    - hs_distribution_file: "IDP-{{ hs_distribution_version }}-lnx{{ hs_distribution_name }}x64"
    - hs_parameterfile_name: parameters_iris20181.isc
    - common_path_to_distribution_files_Cache: "{{ common_path_to_distribution_files }}/iris"
    - hs_cache_usr: cacheusr
    - hs_cache_usr_sys: root
    - hs_cache_group: cacheusr
    - ISC_PACKAGE_UNICODE: Y
    - ISC_BINARY_TYPE: unicode
    - SECURITY_LEVEL: None

  tasks:
  roles:
    - { role: ansible-role-cleanup-sles, when: ansible_os_family == 'Suse'  }
    # - ansible-role-ntp
    - ansible-role-cache
