---
- hosts: all
  gather_facts: True
  vars:
    - hs_distribution_version: 2017.1.0.792.0
    - hs_cache_usr: cacheusr
    - hs_cache_usr_sys: root
    - hs_cache_group: cacheusr
  tasks:
  roles:
    - { role: ansible-role-cleanup-sles, when: ansible_os_family == 'Suse'  }
    - ansible-role-ntp
    - ansible-role-cache
