---
- hosts: all
  gather_facts: true
  tasks:

    - name: "include suse.yaml for key and mail"
      include_vars: suse.yaml

    - name: "add suse registration and container module"
      command: "{{ item }}"
      with_items:
        - "SUSEConnect -r {{ suse_key }} -e {{ suse_mail }}"
        - "SUSEConnect -p sle-module-containers/12/x86_64 -r ''"
      no_log: True
      when: ansible_distribution_version >= '12.0'

    - name: "add suse registration"
      command: "suse_register -a regcode-sles={{ suse_key }} -a email={{ suse_mail }}"
      when: ansible_distribution_version < '12.0'
