# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.box = "elastic/sles-12-x86_64"
  config.vm.box = "toc/sles12sp3"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provider 'virtualbox' do |v|
      v.linked_clone = true
  end

  # map the ports for intersystems cache
  # config.vm.network "forwarded_port", guest: 1972, host: 1972
  # config.vm.network "forwarded_port", guest: 8972, host: 8972

  # disable vbox addons update
  config.vbguest.auto_update = false

  config.vm.synced_folder "/home/jfader/DEVELOPMENT/gits/cambid/docker-intersystems", "/docker"

  # TODO: switch docker storage engine to devicemapper instead of btrfs 

  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.playbook = "ansible/suse-container.yaml"
  end

  # do manual update of vbguest
  config.vm.provision :host_shell do |host_shell|
    host_shell.inline = 'vagrant vbguest --do install'
  end

  # reboot vm
  config.vm.provision :reload

  # # install iris
  # config.vm.provision "ansible" do |ansible|
  #   ansible.become = true
  #   ansible.playbook = "ansible/iris.yaml"
  # end

  # TODO: checkout git-repos and  build basis image for IDP/Caché

  config.vm.provision "shell", inline: <<-SHELL
    cd /docker/sles12
    sudo docker build --build-arg CACHE=IDP-2018.1.0.513.0 -t iris/2018.1.0/sles12sp2 .
  SHELL

end
